spring:
  application:
    name: zhaobiao-service
    jpa:
      database: mysql
      show-sql: true
      hibernate:
        ddl-auto: update
      spring:
        jpa:
          hibernate:
            naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
          properties:
            hibernate:
              dialect: org.hibernate.dialect.MySQL5Dialect
  datasource:
    url: jdbc:mysql://47.107.242.209:3306/where?useUnicode=true&characterEncoding=utf8&autoReconnect=true
    username: root
    password: mofan@123
    driver-class-name: com.mysql.jdbc.Driver
    tomcat:
      max-active: 20
      max-idle: 8
      min-idle: 8
      initial-size: 10

server:
  port: 9001
  servlet:
    context-path: /ty-zhaobiao

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9000/eureka/