server:
  port: 9003

spring:
  datasource:
    url: jdbc:mysql://47.107.242.209:3306/where?useUnicode=true&characterEncoding=utf8&autoReconnect=true
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: mofan@123
    type: com.zaxxer.hikari.HikariDataSource
  #  自动创建更新验证数据库结构
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: mysql

elasticjob:
  serverlists: 127.0.0.1:2181
  namespace: boot-job
